/** Canonical entry-flow routes — single source of truth for navigation targets. */
export const ENTRY_ROUTES = {
  login: '/login',
  loginEmail: '/login/email',
  loginReset: '/login/reset',
  register: '/register',
  callback: '/auth/callback',
  verifyEmail: '/auth/verify-email',
  entry: '/entry',
  workspaceSelect: '/workspace/select',
  workspaceSettings: '/workspace/settings',
  workspaceSettingsProfile: '/workspace/settings/profile',
  workspaceSettingsTeam: '/workspace/settings/team',
  workspaceSettingsNotifications: '/workspace/settings/notifications',
  workspaceSettingsEmailLog: '/workspace/settings/email-log',
  workspaceSettingsMessages: '/workspace/settings/messages',
  workspaceSettingsCrm: '/workspace/settings/crm',
  workspaceSettingsTags: '/workspace/settings/tags',
  workspaceSettingsApiKeys: '/workspace/settings/api-keys',
  workspaceSettingsFiles: '/workspace/settings/files',
  workspaceBusiness: '/workspace/business',
  workspaceBusinessTry: '/workspace/business/try',
  /** @deprecated Prefer {@link ENTRY_ROUTES.workspaceIntegrationsConnections}. */
  workspaceSettingsConnections: '/workspace/integrations/connections',
  /** @deprecated Prefer {@link ENTRY_ROUTES.workspaceIntegrationsChannels}. */
  workspaceSettingsChannels: '/workspace/integrations/channels',
  workspaceIntegrations: '/workspace/integrations',
  workspaceIntegrationsConnections: '/workspace/integrations/connections',
  workspaceIntegrationsChannels: '/workspace/integrations/channels',
  /** Legacy path — app redirects to {@link ENTRY_ROUTES.setup}. */
  onboarding: '/onboarding',
  setup: '/setup',
  dashboard: '/dashboard',
  admin: '/admin',
  adminWorkspaces: '/admin/workspaces',
  adminUsers: '/admin/users',
  crm: '/crm',
  conversations: '/conversations',
  terms: '/terms',
  privacy: '/privacy',
  cookies: '/cookies',
  aiTerms: '/ai-terms',
} as const;

export type EntryRoute = (typeof ENTRY_ROUTES)[keyof typeof ENTRY_ROUTES];
