# syntax=docker/dockerfile:1

FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run db:generate
RUN CI=true npx nx build worker

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/dist/apps/worker/package.json ./package.json
COPY --from=builder /app/dist/apps/worker/main.js ./main.js
RUN npm install --omit=dev

EXPOSE 3334
CMD ["node", "main.js"]
