import { EventType } from '@kodem/contracts';

export const EVENT_TYPES = {
  WORKSPACE_CREATED: 'workspace.created',
  WORKSPACE_UPDATED: 'workspace.updated',
  LEAD_CREATED: 'lead.created',
  LEAD_CONVERTED: 'lead.converted',
  TASK_COMPLETED: 'task.completed',
  INSIGHT_GENERATED: 'insight.generated',
  RECOMMENDATION_GENERATED: 'recommendation.generated',
  DISCOVERY_STARTED: 'discovery.started',
  DISCOVERY_COMPLETED: 'discovery.completed',
  ASSET_DISCOVERED: 'asset.discovered',
  ASSET_PROCESSED: 'asset.processed',
  BUSINESS_UPDATED: 'business.updated',
  SETUP_PREPARATION_REQUESTED: 'setup.preparation.requested',
  CONNECTION_CONNECTED: 'connection.connected',
  CONNECTION_DISCONNECTED: 'connection.disconnected',
  CONNECTION_EXPIRED: 'connection.expired',
  CONNECTION_ERROR: 'connection.error',
  CONNECTION_RECONNECTED: 'connection.reconnected',
  CHANNEL_CONFIGURED: 'channel.configured',
  CHANNEL_DISCONNECTED: 'channel.disconnected',
  MESSAGE_RECEIVED: 'message.received',
  MESSAGE_SENT: 'message.sent',
  MESSAGE_FAILED: 'message.failed',
  CONVERSATION_CREATED: 'conversation.created',
  CONVERSATION_UPDATED: 'conversation.updated',
} as const satisfies Record<string, EventType>;
